### ISSUE TITLE
Couleur des liens du footer. On voit rien

### ISSUE THREAD

**Issue by Edouard-chin** [Blanckette/adamusblanka.github.io#1]
![image](https://github.com/user-attachments/assets/3e893222-0414-4704-a284-6b03e74462b3)

@Blanckette

**Comment by Blanckette** [comment]
Icônes a la place
<img width="440" alt="Capture d’écran 2024-08-27 à 15 04 11" src="https://github.com/user-attachments/assets/ec2170d3-1dd4-48dc-ba8b-b0b271013c86">
